from __future__ import annotations

import json
import re
import subprocess
import zipfile
from dataclasses import asdict, dataclass, field
from pathlib import Path
from typing import Any
from xml.etree import ElementTree

from .storage import append_jsonl, read_json, sha256_file, sha256_tree, write_json_atomic, write_text_atomic, write_yaml_atomic
from .bando_web_research import BandoWebResearcher, WebResearchRequest
from .source_authority import SourceCandidate, assess_authority, infer_official_domains
from .source_fetcher import SourceFetcher
from .source_jury import SourceJury

CATEGORIES = [
    "eligibility", "territory", "deadlines", "expenses", "contribution", "cofinancing",
    "documents", "scoring", "duration", "partnership", "reporting", "exclusions",
]
OFFICIAL_TYPES = {
    "primary_official_document", "official_attachment", "official_amendment", "official_faq",
    "referenced_regulation", "official_operational_manual",
}
FORBIDDEN_SOURCE_MARKERS = ("llm generated", "generated by", "search snippet", "riassunto llm")


@dataclass
class BandoSourceInput:
    path: str
    role: str = "supporting_documents"
    metadata: dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


@dataclass
class BandoBuildRequest:
    primary_document: str | None = None
    attachments: list[str] = field(default_factory=list)
    faq_documents: list[str] = field(default_factory=list)
    amendments: list[str] = field(default_factory=list)
    referenced_regulations: list[str] = field(default_factory=list)
    operational_manuals: list[str] = field(default_factory=list)
    supporting_documents: list[str] = field(default_factory=list)
    output_root: str = "domains"
    force: bool = False

    def sources(self) -> list[BandoSourceInput]:
        pairs = []
        if self.primary_document:
            pairs.append(BandoSourceInput(self.primary_document, "primary_document"))
        for attr, role in (
            ("attachments", "attachments"),
            ("faq_documents", "faq_documents"),
            ("amendments", "amendments"),
            ("referenced_regulations", "referenced_regulations"),
            ("operational_manuals", "operational_manuals"),
            ("supporting_documents", "supporting_documents"),
        ):
            for path in getattr(self, attr):
                pairs.append(BandoSourceInput(path, role))
        return pairs


@dataclass
class BandoDocumentClassification:
    source_id: str
    title: str
    source_type: str
    issuer: str
    path: str
    checksum: str
    published_at: str | None = None
    retrieved_at: str = ""
    binding_level: str = "supporting_not_binding"
    sections_used: list[str] = field(default_factory=list)
    notes: str = ""
    text: str = ""

    def source_record(self) -> dict[str, Any]:
        data = asdict(self)
        data.pop("text", None)
        data["reliability"] = 1.0 if self.binding_level == "binding_official" else 0.6
        return data

    def to_dict(self) -> dict[str, Any]:
        return self.source_record() | {"text_length": len(self.text)}


@dataclass
class BandoIdentityProposal:
    bando_id: str
    title: str
    issuer: str
    edition: str
    version: str = "1.0.0"
    publication_date: str | None = None
    deadline: str | None = None
    territory: str = ""
    status: str = "draft"
    confidence: float = 0.0
    missing_fields: list[str] = field(default_factory=list)

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


@dataclass
class BandoRuleExtraction:
    rules: list[dict[str, Any]]
    uncovered_categories: list[str]
    status: str = "completed"

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


@dataclass
class BandoCalculationExtraction:
    calculations: list[dict[str, Any]]
    ambiguous: list[dict[str, Any]] = field(default_factory=list)

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


@dataclass
class BandoBuildValidation:
    ok: bool
    blocking_issues: list[str] = field(default_factory=list)
    warnings: list[str] = field(default_factory=list)

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


@dataclass
class BandoBuildResult:
    ok: bool
    status: str
    bando_id: str | None = None
    version: str | None = None
    path: str | None = None
    content_hash: str | None = None
    identity: dict[str, Any] = field(default_factory=dict)
    sources: list[dict[str, Any]] = field(default_factory=list)
    rules: list[dict[str, Any]] = field(default_factory=list)
    calculations: list[dict[str, Any]] = field(default_factory=list)
    conflicts: list[dict[str, Any]] = field(default_factory=list)
    missing_documents: list[dict[str, Any]] = field(default_factory=list)
    uncovered_categories: list[str] = field(default_factory=list)
    validation: dict[str, Any] = field(default_factory=dict)
    approval_ready: bool = False
    update_type: str | None = None

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


class BandoDomainBuilder:
    def __init__(self, output_root: str | Path = "domains") -> None:
        self.output_root = Path(output_root)

    def inspect_sources(self, request: BandoBuildRequest | dict[str, Any]) -> list[BandoDocumentClassification]:
        req = _request_from_any(request)
        return [self._inspect_source(src) for src in req.sources()]

    def classify_documents(self, request: BandoBuildRequest | dict[str, Any]) -> list[BandoDocumentClassification]:
        return self.inspect_sources(request)

    def identify_bando(self, documents: list[BandoDocumentClassification]) -> BandoIdentityProposal:
        primary = _primary(documents)
        text = primary.text if primary else ""
        title = _extract_title(text) or (primary.title if primary else "")
        issuer = _extract_issuer(text)
        edition = _extract_edition(text)
        publication_date = _extract_publication_date(text)
        deadline = _extract_deadline(text)
        territory = _extract_territory(text)
        missing = [name for name, value in {"title": title, "issuer": issuer, "edition": edition}.items() if not value]
        bando_id = _slug(" ".join(x for x in (issuer, title, edition) if x)) if not missing else ""
        status = "identity_incomplete" if missing else "draft"
        confidence = 1.0 - (len(missing) * 0.3)
        return BandoIdentityProposal(bando_id, title, issuer, edition, "1.0.0", publication_date, deadline, territory, status, confidence, missing)

    def identify_version(self, identity: BandoIdentityProposal, documents: list[BandoDocumentClassification]) -> str:
        if any(doc.source_type == "official_amendment" for doc in documents):
            return "1.0.1"
        return identity.version

    def extract_rules(self, identity: BandoIdentityProposal, documents: list[BandoDocumentClassification]) -> BandoRuleExtraction:
        primary = _primary(documents)
        if not primary or primary.source_type not in OFFICIAL_TYPES or primary.binding_level != "binding_official":
            return BandoRuleExtraction([], CATEGORIES[:], "incomplete_sources")
        text = _space(primary.text)
        source_id = primary.source_id
        rules: list[dict[str, Any]] = []
        add = lambda rule_id, category, description, field, value, section, excerpt, **kw: rules.append(
            _rule(identity, rule_id, category, description, field, value, source_id, _page_of(primary.text, excerpt), section, excerpt, **kw)
        )
        deadline = _extract_deadline(text)
        if deadline == "no_fixed_deadline":
            add("deadline_no_fixed_deadline", "deadlines", "Call has no fixed deadline.", "deadline", "no_fixed_deadline", "Iter di presentazione", "Il bando è senza scadenza.", priority=200)
        elif deadline:
            add("application_deadline", "deadlines", "Applications must be submitted by the stated deadline.", "deadline", deadline, "Come Partecipare", "presentate dal", priority=200)
        territory = _extract_territory(text)
        if territory:
            add("project_territory", "territory", "Project territory is explicitly constrained.", "territory", territory, "Progetti ammissibili", territory, priority=120)
        min_amount, max_amount = _extract_amount_range(text)
        if min_amount is not None:
            add("contribution_min_amount", "contribution", "Requested contribution minimum.", "contribution_min_amount", min_amount, "Supporto o limiti finanziamento", "compresa", priority=200)
        if max_amount is not None:
            add("contribution_max_amount", "contribution", "Requested contribution maximum.", "contribution_max_amount", max_amount, "Supporto o limiti finanziamento", "compresa", priority=200)
        max_rate = _extract_max_rate(text)
        if max_rate is not None:
            add("contribution_max_rate", "contribution", "Requested contribution maximum rate.", "contribution_max_rate", max_rate, "Supporto o limiti finanziamento", "massimo", priority=200)
        min_rate = _extract_min_rate(text)
        if min_rate is not None:
            add("contribution_min_rate", "contribution", "Requested contribution minimum rate.", "contribution_min_rate", min_rate, "Supporto o limiti finanziamento", "inferiore", priority=200)
        duration = _extract_duration(text)
        if duration:
            add("project_duration_window", "duration", "Project duration window is explicit.", "duration", duration, "Progetti ammissibili", "durata", priority=150)
        eligible = _extract_eligible_subjects(text)
        if eligible:
            add("eligible_applicant_types", "eligibility", "Eligible applicant types are explicit.", "eligibility_applicant_types", eligible, "Soggetti destinatari", "organizzazioni non profit", priority=120)
        if re.search(r"sede legale in Italia", text, re.I):
            add("lead_legal_seat_italy", "eligibility", "Lead applicant legal seat must be in Italy.", "eligibility_lead_legal_seat", "Italy", "Soggetti Ammissibili", "sede legale in Italia", priority=120)
        if re.search(r"Patrimonio netto", text, re.I):
            add("positive_net_equity_required", "eligibility", "Applicant needs positive net equity or approved remediation.", "eligibility_net_equity", "positive_or_remediation", "Soggetti destinatari", "valore positivo di Patrimonio netto", priority=100)
        if re.search(r"partner.*organizzazioni costituite", text, re.I):
            add("partners_must_be_organizations", "partnership", "Partners must be constituted organizations.", "partnership_partner_type", "constituted_organization", "Soggetti Ammissibili", "organizzazioni costituite", priority=100)
        if re.search(r"accordo di partenariato", text, re.I):
            add("partnership_agreement_required", "partnership", "Partnership agreement or equivalent document is required where applicable.", "partnership_agreement", "required_if_partnership", "Soggetti Ammissibili", "accordo di partenariato", priority=100)
        if re.search(r"una proposta|più candidature|più di un", text, re.I):
            add("one_application_per_organization", "partnership", "Organization participation is limited across applications.", "partnership_limit", "one_application_per_organization", "Soggetti Ammissibili", "più candidature", priority=100)
        docs = _extract_required_documents(text)
        if docs:
            add("mandatory_documents", "documents", "Mandatory application documents are explicit.", "documents", docs, "Iter di presentazione", "allegati obbligatori", priority=180)
        if re.search(r"co-?finanziamento", text, re.I):
            add("cofinancing_remaining_costs", "cofinancing", "Remaining costs may be covered by co-financing.", "cofinancing", "required_for_remaining_costs", "Supporto o limiti finanziamento", "co-finanziamento", priority=100)
        if re.search(r"co-?finanziamento", text, re.I) and re.search(r"volontar", text, re.I) and re.search(r"non (è )?ammess", text, re.I):
            add("free_volunteer_work_not_cofinance", "expenses", "Free volunteer work is not admitted as co-financing.", "expenses_cofinance_excluded", "free_volunteer_work", "Costi ammissibili", "volontari", priority=100)
        if re.search(r"co-?finanziamento", text, re.I) and re.search(r"dipendenti|collaboratori|consulenti", text, re.I):
            add("paid_project_work_as_cofinance_allowed", "expenses", "Dedicated paid work can be recognized where explicitly allowed.", "expenses_cofinance_allowed", "paid_project_work", "Costi ammissibili", "dipendenti, collaboratori o consulenti", priority=100)
        if re.search(r"5% dei costi totali", text, re.I):
            add("pre_project_consulting_costs_limit", "expenses", "Pre-project consulting expenses are limited to 5% of total costs.", "expenses_pre_project_consulting_cap", 0.05, "Costi ammissibili", "5% dei costi totali", priority=100)
        scoring = _extract_scoring(text)
        if scoring:
            add("evaluation_criteria", "scoring", "Evaluation criteria are explicit.", "scoring", scoring, "Criteri", "criteri di valutazione", priority=100)
        if re.search(r"rendicont", text, re.I):
            add("reporting_obligations", "reporting", "Reporting duties are indicated but may require operational documents.", "reporting", "reporting_required", "Comunicazioni e informazioni", "rendicontazione", priority=50, interpretation_required=True)
        exclusions = _extract_exclusions(text)
        for idx, value in enumerate(exclusions, 1):
            add(f"exclusion_{idx}", "exclusions", f"Project exclusion: {value}.", "exclusion", value, "Progetti non ammissibili", "Non saranno ammessi", priority=100)
        categories = {rule["category"] for rule in rules}
        uncovered = [cat for cat in CATEGORIES if cat not in categories]
        return BandoRuleExtraction(rules, uncovered)

    def extract_calculations(self, identity: BandoIdentityProposal, documents: list[BandoDocumentClassification]) -> BandoCalculationExtraction:
        primary = _primary(documents)
        if not primary or primary.binding_level != "binding_official":
            return BandoCalculationExtraction([])
        text = _space(primary.text)
        source = primary.source_id
        calculations = []
        ambiguous = []
        max_rate = _extract_max_rate(text)
        min_amount, max_amount = _extract_amount_range(text)
        if max_rate is not None:
            calculations.append({
                "calculation_id": "contribution_percentage",
                "description": "Maximum contribution percentage over total costs.",
                "formula": "total_costs * contribution_rate",
                "required_inputs": ["total_costs", "contribution_rate"],
                "units": {"total_costs": "EUR", "result": "EUR"},
                "source_refs": [source],
                "source_pages": [_page_of(primary.text, "contributo")],
                "minimum": min_amount,
                "maximum": max_amount,
                "cap": max_amount,
                "rounding_policy": "not_specified",
                "percentage": max_rate,
            })
        if max_rate is not None and not re.search(r"costi totali", text, re.I):
            ambiguous.append({"reason": "ambiguous_calculation_basis", "jury_required": True, "source_refs": [source]})
        return BandoCalculationExtraction(calculations, ambiguous)

    def extract_deadlines(self, documents: list[BandoDocumentClassification]) -> dict[str, Any]:
        primary = _primary(documents)
        return {"deadline": _extract_deadline(primary.text if primary else "")}

    def extract_required_documents(self, documents: list[BandoDocumentClassification]) -> list[str]:
        primary = _primary(documents)
        return _extract_required_documents(primary.text if primary else "")

    def extract_conflicts(self, documents: list[BandoDocumentClassification], rules: list[dict[str, Any]]) -> list[dict[str, Any]]:
        conflicts = []
        for doc in documents:
            if doc.source_type == "official_faq" and doc.binding_level == "binding_official":
                for rule in rules:
                    if rule.get("source_refs") and rule["source_refs"][0] != doc.source_id and rule.get("structured_effect", {}).get("value") in doc.text:
                        conflicts.append({
                            "conflict_id": f"faq_conflict:{rule['rule_id']}",
                            "rule_id": rule["rule_id"],
                            "source_refs": [rule["source_refs"][0], doc.source_id],
                            "description": "Potential FAQ conflict requires review.",
                            "blocking": True,
                            "status": "conflicting_official_documents",
                        })
        return conflicts

    def build_tests(self, identity: BandoIdentityProposal, rules: list[dict[str, Any]]) -> list[dict[str, Any]]:
        tests = []
        for rule in rules:
            field = rule.get("field") or rule.get("structured_effect", {}).get("field")
            if field in {"deadline", "territory", "contribution_max_rate", "contribution_max_amount"}:
                tests.append({
                    "test_id": f"{rule['rule_id']}_deterministic",
                    "kind": "deterministic",
                    "input": {"field": field},
                    "expected": {"value": rule.get("value") or rule.get("structured_effect", {}).get("value")},
                    "source_refs": rule.get("source_refs", []),
                })
        return tests

    def build_draft(self, request: BandoBuildRequest | dict[str, Any]) -> BandoBuildResult:
        req = _request_from_any(request)
        self.output_root = Path(req.output_root)
        docs = self.classify_documents(req)
        identity = self.identify_bando(docs)
        identity.version = self.identify_version(identity, docs)
        if identity.status == "identity_incomplete":
            return BandoBuildResult(False, "identity_incomplete", identity=identity.to_dict(), sources=[d.source_record() for d in docs], missing_documents=_missing_docs(docs), validation={"blocking_issues": identity.missing_fields}, approval_ready=False)
        rules_extraction = self.extract_rules(identity, docs)
        calculations = self.extract_calculations(identity, docs)
        conflicts = self.extract_conflicts(docs, rules_extraction.rules)
        validation = self.validate_draft(identity, docs, rules_extraction, calculations, conflicts)
        path = self.output_root / "drafts" / "bandi" / identity.bando_id / identity.version
        self._write_draft(path, identity, docs, rules_extraction, calculations, conflicts)
        self._upsert_registry(identity, path)
        content_hash = sha256_tree(path)
        return BandoBuildResult(
            True,
            "draft_created" if validation.ok else "incomplete_sources",
            identity.bando_id,
            identity.version,
            str(path),
            content_hash,
            identity.to_dict(),
            [d.source_record() for d in docs],
            rules_extraction.rules,
            calculations.calculations,
            conflicts,
            _missing_docs(docs),
            rules_extraction.uncovered_categories,
            validation.to_dict(),
            validation.ok,
        )

    def update_draft(self, request: BandoBuildRequest | dict[str, Any]) -> BandoBuildResult:
        return self.build_draft(request)

    def validate_draft(self, identity: BandoIdentityProposal, documents: list[BandoDocumentClassification] | None = None, rules: BandoRuleExtraction | None = None, calculations: BandoCalculationExtraction | None = None, conflicts: list[dict[str, Any]] | None = None) -> BandoBuildValidation:
        issues = []
        warnings = []
        documents = documents or []
        rules = rules or BandoRuleExtraction([], CATEGORIES[:])
        conflicts = conflicts or []
        if identity.status == "identity_incomplete":
            issues.extend(identity.missing_fields)
        if not _primary(documents):
            issues.append("primary_source_missing")
        if not rules.rules:
            issues.append("rules_missing")
        if conflicts:
            issues.append("conflicting_official_documents")
        if rules.uncovered_categories:
            warnings.extend(f"uncovered:{cat}" for cat in rules.uncovered_categories)
        return BandoBuildValidation(not issues, issues, warnings)

    def compare_versions(self, bando_id: str, from_version: str, to_version: str, root: str | Path | None = None) -> dict[str, Any]:
        base = Path(root) if root else self.output_root
        left = _load_manifest(base / "drafts" / "bandi" / bando_id / from_version / "domain.yaml")
        right = _load_manifest(base / "drafts" / "bandi" / bando_id / to_version / "domain.yaml")
        if not left or not right:
            return {"status": "missing_version", "bando_id": bando_id}
        if left.get("edition") != right.get("edition"):
            update_type = "new_edition"
        elif from_version != to_version:
            update_type = "new_version"
        elif left.get("rule_set_hash") != right.get("rule_set_hash"):
            update_type = "rule_update"
        else:
            update_type = "document_update" if left.get("source_hash") != right.get("source_hash") else "unchanged"
        return {"status": "ok", "bando_id": bando_id, "from": from_version, "to": to_version, "update_type": update_type}

    def discover_missing_sources(self, bando_id: str, version: str) -> dict[str, Any]:
        manifest = self._load_bando_manifest(bando_id, version)
        if not manifest:
            return {"status": "missing_context", "bando_id": bando_id, "version": version, "missing_documents": []}
        present = {item.get("source_type") for item in manifest.get("official_sources", [])}
        present.update(item.get("source_type") for item in manifest.get("faq", []))
        present.update(item.get("source_type") for item in manifest.get("amendments", []))
        wanted = {
            "official_faq": "FAQ ufficiale",
            "official_amendment": "rettifica ufficiale",
            "official_deadline_extension": "proroga ufficiale",
            "official_post_selection_agreement": "accordo post-selezione",
            "official_reporting_manual": "manuale di rendicontazione",
            "official_attachment": "allegati ufficiali",
            "official_application_form": "formulario ufficiale",
            "official_budget_template": "budget ufficiale",
        }
        missing = [{"document_type": key, "label": label, "status": "not_found"} for key, label in wanted.items() if key not in present]
        return {"status": "ok", "bando_id": bando_id, "version": version, "missing_documents": missing}

    def research_web(self, bando_id: str, version: str, *, allow_web: bool = False, offline: bool = False, provider=None, fetcher: SourceFetcher | None = None) -> dict[str, Any]:
        manifest = self._load_bando_manifest(bando_id, version)
        if not manifest:
            return {"status": "missing_context", "bando_id": bando_id, "version": version}
        missing = self.discover_missing_sources(bando_id, version).get("missing_documents", [])
        request = WebResearchRequest.from_env(
            bando_id=bando_id,
            version=version,
            title=manifest.get("title") or manifest.get("display_name") or "",
            issuer=manifest.get("issuer") or "",
            edition=manifest.get("edition") or "",
            territory=manifest.get("territory") or "",
            official_domain=(infer_official_domains(manifest.get("issuer") or "") or [""])[0],
            missing_documents=[item["document_type"] for item in missing],
            allow_web=allow_web,
            offline=offline,
        )
        result = BandoWebResearcher(provider=provider, fetcher=fetcher).research(request)
        out = result.to_dict()
        out["missing_documents"] = missing
        return out

    def assess_source_candidates(self, candidates: list[dict[str, Any]], *, issuer: str = "") -> dict[str, Any]:
        jury = SourceJury()
        assessments = []
        for row in candidates:
            candidate = SourceCandidate(**row)
            authority = assess_authority(candidate, issuer=issuer)
            assessments.append({"candidate": candidate.to_dict(), "authority": authority.to_dict(), "jury": jury.assess(candidate, authority).to_dict()})
        return {"status": "ok", "assessments": assessments}

    def fetch_approved_sources(self, candidates: list[dict[str, Any]], *, cache_dir: str = ".ralf_run/bando_web_cache") -> dict[str, Any]:
        fetcher = SourceFetcher(cache_dir=cache_dir)
        fetched = [fetcher.fetch(item["url"]).to_dict() for item in candidates if item.get("url")]
        return {"status": "ok", "fetched_sources": fetched}

    def merge_source_sets(self, local_sources: list[dict[str, Any]], web_sources: list[dict[str, Any]]) -> dict[str, Any]:
        jury = SourceJury()
        merged = list(local_sources)
        conflicts = []
        seen = {item.get("checksum") for item in local_sources if item.get("checksum")}
        for web in web_sources:
            checksum = web.get("checksum") or web.get("fetch", {}).get("checksum")
            if checksum and checksum in seen:
                continue
            for local in local_sources:
                conflict = jury.assess_conflict(local, {"checksum": checksum, "version": web.get("version")}).to_dict()
                if conflict["status"] != "same_document":
                    conflicts.append(conflict)
            merged.append(web)
        return {"status": "ok", "sources": merged, "conflicts": conflicts, "validation_required": bool(conflicts or web_sources)}

    def rebuild_with_discovered_sources(self, bando_id: str, version: str, *, allow_web: bool = False, offline: bool = False, provider=None) -> dict[str, Any]:
        result = self.research_web(bando_id, version, allow_web=allow_web, offline=offline, provider=provider)
        if result.get("status") in {"web_disabled", "search_provider_unavailable", "no_candidates", "sources_rejected"}:
            return result
        return {
            "status": "validation_required" if result.get("accepted_sources") else result.get("status", "not_found"),
            "bando_id": bando_id,
            "version": version,
            "new_documents": result.get("new_documents", []),
            "accepted_sources": result.get("accepted_sources", []),
            "human_review_required": True,
            "active_modified": False,
        }

    def _load_bando_manifest(self, bando_id: str, version: str) -> dict[str, Any]:
        path = self.output_root / "drafts" / "bandi" / bando_id / version / "domain.yaml"
        return _load_manifest(path)

    def _inspect_source(self, source: BandoSourceInput) -> BandoDocumentClassification:
        path = Path(source.path)
        text = _extract_text(path)
        title = _extract_title(text) or path.stem.replace("_", " ")
        issuer = _extract_issuer(text)
        source_type = _classify_type(source.role, text)
        binding = "binding_official" if source_type in OFFICIAL_TYPES and source_type not in {"official_attachment"} and not _forbidden_source(text) else "supporting_not_binding"
        if source_type == "official_attachment":
            binding = "binding_official"
        if _forbidden_source(text):
            source_type = "supporting_document"
            binding = "supporting_not_binding"
        source_id = _slug(f"{source_type} {title}")[:80]
        return BandoDocumentClassification(source_id, title, source_type, issuer, str(path), sha256_file(path) if path.is_file() else "", _extract_publication_date(text), "", binding, _sections(text), "", text)

    def _write_draft(self, path: Path, identity: BandoIdentityProposal, docs: list[BandoDocumentClassification], rules: BandoRuleExtraction, calculations: BandoCalculationExtraction, conflicts: list[dict[str, Any]]) -> None:
        for folder in ["rules", "decision_tables", "calculations", "examples", "tests"]:
            (path / folder).mkdir(parents=True, exist_ok=True)
        rule_hash = _hash_json(rules.rules)
        manifest = {
            "domain_id": f"bandi/{identity.bando_id}",
            "bando_id": identity.bando_id,
            "title": identity.title,
            "display_name": identity.title,
            "issuer": identity.issuer,
            "edition": identity.edition,
            "version": identity.version,
            "status": "draft",
            "state": "draft",
            "publication_date": identity.publication_date,
            "deadline": identity.deadline,
            "territory": identity.territory,
            "beneficiaries": [],
            "official_sources": [doc.source_record() for doc in docs if doc.binding_level == "binding_official"],
            "faq": [doc.source_record() for doc in docs if doc.source_type == "official_faq"],
            "amendments": [doc.source_record() for doc in docs if doc.source_type == "official_amendment"],
            "rule_set_hash": rule_hash,
            "schema_version": "1.0",
            "created_at": "",
            "updated_at": "",
            "scope": [identity.title, "bando-specific rules"],
            "out_of_scope": ["other editions", "missing official documents", "runtime activation"],
            "minimum_source_count": 1,
            "minimum_test_pass_rate": 1.0,
            "content_hash": "",
        }
        write_yaml_atomic(path / "domain.yaml", manifest)
        write_text_atomic(path / "sources.jsonl", "")
        for doc in docs:
            append_jsonl(path / "sources.jsonl", doc.source_record())
        by_cat = {cat: [] for cat in CATEGORIES}
        for rule in rules.rules:
            by_cat.setdefault(rule["category"], []).append(rule)
        for cat in CATEGORIES:
            write_yaml_atomic(path / "rules" / f"{cat}.yaml", {"rules": by_cat.get(cat, [])})
        write_text_atomic(path / "conflicts.jsonl", "")
        for conflict in conflicts:
            append_jsonl(path / "conflicts.jsonl", conflict)
        for calc in calculations.calculations:
            write_yaml_atomic(path / "calculations" / f"{calc['calculation_id']}.yaml", calc)
        if not calculations.calculations:
            write_text_atomic(path / "calculations" / ".gitkeep", "")
        write_yaml_atomic(path / "decision_tables" / "coverage.yaml", {"table_id": "coverage", "rows": [{"category": cat, "covered": cat not in rules.uncovered_categories} for cat in CATEGORIES]})
        write_text_atomic(path / "examples" / "examples.jsonl", json.dumps({"example_id": "draft_scope", "source_refs": [d.source_id for d in docs if d.binding_level == "binding_official"]}, sort_keys=True) + "\n")
        tests = self.build_tests(identity, rules.rules)
        write_text_atomic(path / "tests" / "tests.jsonl", "".join(json.dumps(t, sort_keys=True, ensure_ascii=False) + "\n" for t in tests))
        write_text_atomic(path / "manual.md", f"# {identity.title}\n\nDraft generated from official documents. Missing categories remain uncovered.\n")
        write_text_atomic(path / "glossary.md", "# Glossary\n\n- bando: official call.\n")
        write_text_atomic(path / "CHANGELOG.md", "# Changelog\n\n- 1.0.0 draft generated from local official documents.\n")
        write_text_atomic(path / "manifest.sha256", sha256_tree(path) + "\n")

    def _upsert_registry(self, identity: BandoIdentityProposal, path: Path) -> None:
        registry_path = self.output_root / "registry.json"
        data = read_json(registry_path) or {"domains": []}
        row = {"domain_id": f"bandi/{identity.bando_id}", "version": identity.version, "state": "draft", "path": str(path.resolve())}
        data["domains"] = [item for item in data.get("domains", []) if not (item.get("domain_id") == row["domain_id"] and item.get("version") == row["version"])]
        data["domains"].append(row)
        data["domains"].sort(key=lambda item: (item.get("domain_id", ""), item.get("version", ""), item.get("state", "")))
        write_json_atomic(registry_path, data)


def _request_from_any(value: BandoBuildRequest | dict[str, Any]) -> BandoBuildRequest:
    if isinstance(value, BandoBuildRequest):
        return value
    return BandoBuildRequest(**value)


def _extract_text(path: Path) -> str:
    if not path.exists():
        return ""
    suffix = path.suffix.lower()
    if suffix == ".pdf":
        try:
            proc = subprocess.run(["pdftotext", "-layout", str(path), "-"], check=False, stdout=subprocess.PIPE, stderr=subprocess.DEVNULL, text=True, timeout=30)
            if proc.returncode == 0 and proc.stdout.strip():
                return proc.stdout
        except (OSError, subprocess.TimeoutExpired):
            pass
    if suffix == ".docx":
        try:
            with zipfile.ZipFile(path) as archive:
                xml = archive.read("word/document.xml")
            root = ElementTree.fromstring(xml)
            return " ".join(node.text or "" for node in root.iter() if node.text)
        except Exception:
            return ""
    return path.read_text(encoding="utf-8", errors="replace")


def _classify_type(role: str, text: str) -> str:
    low = text.lower()
    if role == "amendments" or "rettifica" in low:
        return "official_amendment"
    if role == "faq_documents" or re.search(r"\bfaq\b|domande frequenti", low):
        return "official_faq"
    if role == "referenced_regulations":
        return "referenced_regulation"
    if role == "operational_manuals" or "manuale" in low:
        return "official_operational_manual"
    if role == "attachments":
        return "official_attachment"
    if role == "primary_document" and "bando" in low:
        return "primary_official_document"
    return "supporting_document"


def _forbidden_source(text: str) -> bool:
    low = text.lower()
    return any(marker in low for marker in FORBIDDEN_SOURCE_MARKERS)


def _primary(documents: list[BandoDocumentClassification]) -> BandoDocumentClassification | None:
    for doc in documents:
        if doc.source_type == "primary_official_document":
            return doc
    for doc in documents:
        if doc.binding_level == "binding_official":
            return doc
    return documents[0] if documents else None


def _extract_title(text: str) -> str:
    lines = [ln.strip(" \t-_–") for ln in text.splitlines() if ln.strip(" \t-_–")]
    for pat in (r"Il Bando\s+([^\n]+?)\s+di\s+Fondazione", r"bando[ \"“]+([^\n”]+)[\"”]", r"^([A-ZÀ-Ú][\wÀ-ÿ' ]{3,80})$"):
        m = re.search(pat, text, re.I | re.M)
        if m:
            return _clean_title(m.group(1))
    return _clean_title(" ".join(lines[:2])) if lines else ""


def _clean_title(value: str) -> str:
    value = re.sub(r"\s+", " ", value.replace("–", "-")).strip(" -.")
    value = re.sub(r"\s*\(.*?di seguito.*$", "", value, flags=re.I)
    value = re.sub(r"\s+di seguito.*$", "", value, flags=re.I)
    return value[:140]


def _extract_issuer(text: str) -> str:
    m = re.search(r"Fondazione\s+[A-ZÀ-Ú][\wÀ-ÿ]+", text)
    return re.sub(r"\s+", " ", m.group(0)).strip() if m else ""


def _extract_edition(text: str) -> str:
    for pat in (r"BANDI\s+(20\d{2})", r"Regolamento\s+(20\d{2})", r"edizione\s+(20\d{2})", r"(20\d{2})"):
        m = re.search(pat, text, re.I)
        if m:
            return m.group(1)
    return ""


def _extract_publication_date(text: str) -> str | None:
    m = re.search(r"(\d{1,2})\s+(gennaio|febbraio|marzo|aprile|maggio|giugno|luglio|agosto|settembre|ottobre|novembre|dicembre)\s+(20\d{2})", text, re.I)
    return _it_date(m) if m else None


def _extract_deadline(text: str) -> str | None:
    if re.search(r"senza\s+scadenza", text, re.I):
        return "no_fixed_deadline"
    deadline_table = re.search(
        r"Scadenza(?P<body>.{0,220}?ore\s*(?P<hour>\d{1,2}))",
        text,
        re.I | re.S,
    )
    if deadline_table:
        dates = list(
            re.finditer(
                r"(\d{1,2})\s+(gennaio|febbraio|marzo|aprile|maggio|giugno|luglio|agosto|settembre|ottobre|novembre|dicembre)\s+(20\d{2})",
                deadline_table.group("body"),
                re.I,
            )
        )
        if dates:
            date = _it_date(dates[-1])
            return f"{date}T{int(deadline_table.group('hour')):02d}:00:00+02:00"
    submission = re.search(
        r"\bal\s+(\d{1,2})\s+(gennaio|febbraio|marzo|aprile|maggio|giugno|luglio|agosto|settembre|ottobre|novembre|dicembre)\s+(20\d{2}).{0,80}?ore\s*(\d{1,2})",
        text,
        re.I | re.S,
    )
    if submission:
        date = _it_date(submission)
        return f"{date}T{int(submission.group(4)):02d}:00:00+02:00"
    matches = list(re.finditer(r"(\d{1,2})\s+(gennaio|febbraio|marzo|aprile|maggio|giugno|luglio|agosto|settembre|ottobre|novembre|dicembre)\s+(20\d{2})(?:[^\n]{0,80}?ore\s*(\d{1,2}))?", text, re.I))
    if not matches:
        return None
    m = matches[-1]
    date = _it_date(m)
    hour = m.group(4)
    return f"{date}T{int(hour):02d}:00:00+02:00" if hour else date


def _it_date(match: re.Match[str]) -> str:
    months = {"gennaio": 1, "febbraio": 2, "marzo": 3, "aprile": 4, "maggio": 5, "giugno": 6, "luglio": 7, "agosto": 8, "settembre": 9, "ottobre": 10, "novembre": 11, "dicembre": 12}
    return f"{match.group(3)}-{months[match.group(2).lower()]:02d}-{int(match.group(1)):02d}"


def _extract_territory(text: str) -> str:
    if re.search(r"Lombardia.*Novara.*Verbano", text, re.I | re.S):
        return "Lombardia; Novara; Verbano-Cusio-Ossola"
    if re.search(r"realizzat[ie]?\s+in\s+Italia|sede legale in Italia", text, re.I):
        return "Italy"
    return ""


def _extract_amount_range(text: str) -> tuple[int | None, int | None]:
    m = re.search(r"(?:compres[ao]|tra|fra)\s+(?:i\s+)?(?:€\s*)?([\d.]{2,})\s*(?:euro)?\s*(?:e|ed|-)\s+(?:i\s+)?(?:€\s*)?([\d.]{2,})", text, re.I)
    if not m:
        anchor = re.search(r"(?:richiesta|contributo)[^.]{0,220}?(?:compres[ao]|tra|fra)", text, re.I)
        if not anchor:
            return None, None
        amounts = re.findall(r"(?:€\s*)?(\d{2,3}(?:\.\d{3})+|\d{5,})", text[anchor.start() : anchor.start() + 360])
        if len(amounts) < 2:
            return None, None
        return _money(amounts[0]), _money(amounts[1])
    return _money(m.group(1)), _money(m.group(2))


def _money(value: str) -> int:
    raw = value.replace(".", "")
    return int(raw)


def _extract_max_rate(text: str) -> float | None:
    m = re.search(r"massimo\s+del\s+(\d{1,3})%|superiore\s+al\s+(\d{1,3})%", text, re.I)
    if not m:
        return None
    return int(m.group(1) or m.group(2)) / 100


def _extract_min_rate(text: str) -> float | None:
    m = re.search(r"inferiore\s+(?:ad\s+almeno\s+)?(?:al\s+)?(\d{1,3})%", text, re.I)
    return int(m.group(1)) / 100 if m else None


def _extract_duration(text: str) -> dict[str, Any] | None:
    m = re.search(r"durata[^.]{0,80}?compresa\s+tra\s+(\d+)\s+e\s+(\d+)\s+mesi", text, re.I)
    if m:
        return {"min_months": int(m.group(1)), "max_months": int(m.group(2))}
    m = re.search(r"durata[^.]{0,160}?(\d+)\s+e\s+(\d+)\s+mesi", text, re.I)
    if m:
        return {"min_months": int(m.group(1)), "max_months": int(m.group(2))}
    m = re.search(r"durata\s+massima\s+di\s+(\d+)\s+mesi", text, re.I)
    if m:
        return {"max_months": int(m.group(1))}
    return None


def _extract_eligible_subjects(text: str) -> list[str]:
    if re.search(r"organizzazioni\s+non\s+profit", text, re.I):
        return ["organizzazioni non profit"]
    bullets = re.findall(r"•\s+([^\n]{5,80})", text)
    return [b.strip(" .;") for b in bullets[:8] if re.search(r"associazioni|enti|cooperative|imprese", b, re.I)]


def _extract_required_documents(text: str) -> list[str]:
    docs = []
    for key, label in (("budget", "budget"), ("quadro logico", "logical_framework"), ("statuto", "statute"), ("accordo", "partnership_agreement"), ("lettere di adesione", "support_letters"), ("dichiarazione", "declaration")):
        if re.search(key, text, re.I):
            docs.append(label)
    return sorted(set(docs))


def _extract_scoring(text: str) -> list[str]:
    keys = []
    for token in ("coerenza", "qualità", "impatto", "innovazione", "rete", "sostenibilità", "monitoraggio"):
        if token in text.lower():
            keys.append(token)
    return keys


def _extract_exclusions(text: str) -> list[str]:
    out = []
    if re.search(r"mera\s+ricerca", text, re.I):
        out.append("mere_research")
    if re.search(r"grandi\s+eventi\s+episodici", text, re.I):
        out.append("large_episodic_events")
    if re.search(r"esclusivamente\s+in\s+ambito\s+scolastico", text, re.I):
        out.append("school_only_children_activities")
    if re.search(r"attività\s+formative\s+rivolte\s+agli\s+operatori", text, re.I):
        out.append("operator_training_only")
    if re.search(r"oltre\s+tale\s+limite", text, re.I):
        out.append("late_or_wrong_modality_submission")
    return out


def _rule(identity: BandoIdentityProposal, rule_id: str, category: str, description: str, field: str, value: Any, source_id: str, page: int, section: str, excerpt: str, priority: int = 100, interpretation_required: bool = False) -> dict[str, Any]:
    return {
        "rule_id": rule_id,
        "bando_id": identity.bando_id,
        "version": identity.version,
        "category": category,
        "description": description,
        "structured_condition": {},
        "structured_effect": {"field": field, "value": value},
        "exceptions": [],
        "source_refs": [source_id],
        "source_pages": [page],
        "source_sections": [section],
        "source_excerpt_short": _short(excerpt),
        "priority": priority,
        "confidence": 1.0,
        "interpretation_required": interpretation_required,
        "blocking": False,
        "enabled": True,
        "field": field,
        "value": value,
        "source_ref": source_id,
        "document_type": "official_call_text",
    }


def _page_of(text: str, needle: str) -> int:
    idx = text.lower().find(str(needle).lower()) if needle else -1
    return text[:idx].count("\f") + 1 if idx >= 0 else 1


def _sections(text: str) -> list[str]:
    return [m.group(0).strip() for m in re.finditer(r"^\s*\d+(?:\.\d+)?\.\s+[^\n]{3,80}", text, re.M)][:16]


def _short(text: str) -> str:
    words = re.sub(r"\s+", " ", str(text)).strip().split()
    return " ".join(words[:25])


def _space(text: str) -> str:
    return re.sub(r"\s+", " ", text)


def _slug(text: str) -> str:
    import unicodedata
    normalized = unicodedata.normalize("NFKD", text).encode("ascii", "ignore").decode("ascii")
    normalized = re.sub(r"[^a-zA-Z0-9]+", "_", normalized.lower()).strip("_")
    return normalized[:96]


def _hash_json(value: Any) -> str:
    return __import__("hashlib").sha256(json.dumps(value, sort_keys=True, ensure_ascii=False, default=str).encode()).hexdigest()


def _load_manifest(path: Path) -> dict[str, Any]:
    import yaml
    return yaml.safe_load(path.read_text(encoding="utf-8")) if path.exists() else {}


def _missing_docs(documents: list[BandoDocumentClassification]) -> list[dict[str, str]]:
    types = {doc.source_type for doc in documents}
    missing = []
    if "official_faq" not in types:
        missing.append({"document": "official_faq", "impact": "validation_required_when_available"})
    if "official_amendment" not in types:
        missing.append({"document": "official_amendments", "impact": "validation_required_when_available"})
    return missing
